### ISSUE TITLE
aks - ignoreChanges on subnet route table

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-self-hosted-installers#99]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Currently, when AKS creates a managed cluster, it mutates the given subnet by adding a route table. This can be problematic if the program has explicitly created the vnet/subnet/etc prior to creating the AKS cluster. Effectively, Pulumi's view of the subnet will always be out of date from what is present in Azure. Running a refresh and up on the subnet results in the cluster routetable being removed, which results in broken cluster DNS.

The issue is further described [here](https://www.jfe.cloud/the-case-of-the-missing-aks-route-table-assignment/).

### Affected area/feature
Ultimately, we should be setting ignoreChanges on the `subnet.routetable` property or whatever it is called to stop Pulumi from caring if the routetable changes.

**Comment by phillipedwards** [comment]
Updating the subnet resource in `aks-hosted/01-infrastructure/network.ts` to 
```
 const subnet = new network.Subnet(`${name}-snet`, {
      resourceGroupName: args.resourceGroupName,
      virtualNetworkName: vnet.name,
      addressPrefix: args.subnetCidr,
      serviceEndpoints: [{
        service: "Microsoft.Sql"
      }],
    }, {
      parent: vnet,
      ignoreChanges: ["routeTable.id"]
    });
   
```

should stop this from occurring.

**Comment by pierskarsenbarg** [comment]
@phillipedwards for the v2 one, it looks like the Azure CNI is going to be the way forward with networking (mainly because it allows improved routing between subnets which is something I think we're going to need for the flexible MySQL servers). Here's the required change: https://github.com/pulumi/pulumi-self-hosted-installers/pull/98/commits/4227616046b99b69547cc3688842647eed030b6b

There's a note at the top of the blog post that says if you use the Azure CNI then there's no route table involved.

**Comment by pierskarsenbarg** [comment]
So I've tested this now with the Azure CNI and instead it adds a load of ipconfigurations to the subnets which I think is ok.
